[package]
name = "sniper-shared"
version = "11.1.0"
edition = "2024"

[lib]
name = "sniper_types"
path = "src/lib.rs"

[dependencies]
memmap2 = "0.9.5"
zerocopy = { version = "0.8.14", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
tracing-appender = "0.2"
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
