#!/usr/bin/env python3
"""
🛡️ BEROUN L1 SHIELD v9.2 — Tactical GPU AI Sidecar
═══════════════════════════════════════════════════
Architecture: Reads orderbook from mmap, writes skew + freeze back
  - OBI Micro-Skewing: shifts grid bias based on order book imbalance
  - Sweep Protection: detects large sweeps and freezes execution
  - Toxic Flow Detection: tracks adverse selection patterns

Latency: <1ms cycle (reads atomics from /dev/shm/beroun/)
Communication: mmap atomics (zero-copy, zero-latency)
═══════════════════════════════════════════════════
"""

import mmap
import struct
import time
import sys
import os
import signal
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [L1] %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('/home/wwwenda/hft-sniper/logs/l1_shield.log')
    ]
)
log = logging.getLogger('L1')

# ═══ MMAP OFFSETS — AUTO-GENERATED BY dump-offsets (Rust-verified) ═══
# Total struct size: 1600 bytes, Align: 64 bytes
# OrderBookLevel = 3 × AtomicU64/I64 = 24 bytes (price:8 + amount:8 + count:8)
ENGINE_MMAP = "/dev/shm/beroun/engine_state.bin"
PRICE_SCALE = 1e8

OFF_BEST_BID = 64
OFF_BEST_ASK = 72
OFF_BIDS = 80         # bids[25], each 24 bytes = 600 bytes total
OFF_ASKS = 680        # asks[25], each 24 bytes = 600 bytes total
OFF_MICRO = 1288      # micro_price
OFF_OBI = 1384        # l2_imbalance
OFF_TOXIC = 1568      # toxic_flow_hits
OFF_SWEEP_FREEZE = 1576  # sweep_freeze_until
OFF_L1_SKEW = 1584    # l1_skew_adjustment
OBL_SIZE = 24         # sizeof(OrderBookLevel) = 3 × 8 bytes

# ═══ CONFIGURATION ═══
CYCLE_MS = 50           # 50ms cycle = 20 updates/sec
OBI_SKEW_FACTOR = 0.3   # How aggressively to skew based on OBI (0.0-1.0)
MAX_SKEW_USD = 3.0       # Maximum skew in USD
SWEEP_VOL_DROP_PCT = 0.70 # 70% depth volume drop = genuine sweep
SWEEP_FREEZE_MS = 15000  # 15 second freeze after sweep
SWEEP_DEBOUNCE_MS = 500  # Ignore sweeps within 500ms of last one
BOOK_DEPTH = 10          # Read top 10 of 25 levels for stable depth measurement

running = True

def signal_handler(sig, frame):
    global running
    log.info("Shutting down L1 Shield...")
    running = False

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)


def read_u64(mm, offset):
    return struct.unpack_from('<Q', mm, offset)[0]

def read_i64(mm, offset):
    return struct.unpack_from('<q', mm, offset)[0]

def write_u64(mm, offset, val):
    struct.pack_into('<Q', mm, offset, val)

def write_i64(mm, offset, val):
    struct.pack_into('<q', mm, offset, val)


def read_orderbook_levels(mm, base_offset, n=5):
    """Read n OrderBookLevel from mmap. Each level is OBL_SIZE (60) bytes."""
    levels = []
    for i in range(n):
        off = base_offset + i * OBL_SIZE  # 60 bytes per level
        price = read_u64(mm, off) / PRICE_SCALE
        amount = read_i64(mm, off + 8) / PRICE_SCALE
        if price > 0:
            levels.append((price, amount))
    return levels


def compute_obi(bids, asks, depth=3):
    """Order Book Imbalance: (bid_vol - ask_vol) / (bid_vol + ask_vol)."""
    bid_vol = sum(abs(a) for _, a in bids[:depth])
    ask_vol = sum(abs(a) for _, a in asks[:depth])
    total = bid_vol + ask_vol
    if total < 1e-10:
        return 0.0
    return (bid_vol - ask_vol) / total  # +1 = strong bids, -1 = strong asks


def detect_sweep(prev_levels, curr_levels):
    """Detect sweep by comparing total depth volume drop between cycles."""
    if not prev_levels or not curr_levels:
        return False
    prev_vol = sum(abs(a) for _, a in prev_levels)
    curr_vol = sum(abs(a) for _, a in curr_levels)
    if prev_vol < 0.001:  # no meaningful depth
        return False
    drop = (prev_vol - curr_vol) / prev_vol
    return drop > SWEEP_VOL_DROP_PCT


def main():
    global running

    log.info("═══ L1 SHIELD v9.2 STARTING ═══")
    log.info(f"  mmap: {ENGINE_MMAP}")
    log.info(f"  Cycle: {CYCLE_MS}ms | Skew factor: {OBI_SKEW_FACTOR}")
    log.info(f"  Max skew: ${MAX_SKEW_USD} | Sweep freeze: {SWEEP_FREEZE_MS}ms")

    if not os.path.exists(ENGINE_MMAP):
        log.error(f"Engine mmap not found: {ENGINE_MMAP}")
        sys.exit(1)

    fd = os.open(ENGINE_MMAP, os.O_RDWR)
    mm = mmap.mmap(fd, 0, access=mmap.ACCESS_WRITE)

    prev_bids = []
    prev_asks = []
    last_sweep_ms = 0  # debounce timestamp
    cycle = 0

    log.info("═══ L1 SHIELD ACTIVE ═══")

    while running:
        try:
            t0 = time.monotonic()

            # ── READ ORDERBOOK ──
            bids = read_orderbook_levels(mm, OFF_BIDS, BOOK_DEPTH)
            asks = read_orderbook_levels(mm, OFF_ASKS, BOOK_DEPTH)

            # ── OBI MICRO-SKEWING ──
            obi = compute_obi(bids, asks, depth=3)

            # OBI > 0 → strong bids → push asks higher (buyer's market, be greedy)
            # OBI < 0 → strong asks → pull bids lower (seller pressure, be cautious)
            skew_usd = obi * OBI_SKEW_FACTOR * MAX_SKEW_USD
            skew_usd = max(-MAX_SKEW_USD, min(MAX_SKEW_USD, skew_usd))
            skew_scaled = int(skew_usd * PRICE_SCALE)

            write_i64(mm, OFF_L1_SKEW, skew_scaled)

            # ── SWEEP PROTECTION (with debounce) ──
            if cycle > 5:  # skip first cycles for stabilization
                now_ms = int(time.time() * 1000)
                if now_ms - last_sweep_ms > SWEEP_DEBOUNCE_MS:  # debounce
                    bid_sweep = detect_sweep(prev_bids, bids)
                    ask_sweep = detect_sweep(prev_asks, asks)

                    if bid_sweep or ask_sweep:
                        side = "BID" if bid_sweep else "ASK"
                        freeze_until = now_ms + SWEEP_FREEZE_MS
                        write_u64(mm, OFF_SWEEP_FREEZE, freeze_until)
                        last_sweep_ms = now_ms

                        # Sanity-checked increment of toxic_flow_hits
                        current_toxic = read_u64(mm, OFF_TOXIC)
                        if current_toxic > 1_000_000:  # corrupted → reset
                            write_u64(mm, OFF_TOXIC, 1)
                            current_toxic = 0
                        else:
                            write_u64(mm, OFF_TOXIC, current_toxic + 1)

                        log.warning(f"🚨 SWEEP ({side})! Freeze {SWEEP_FREEZE_MS}ms. "
                                   f"Toxic: {current_toxic + 1}")

            prev_bids = bids
            prev_asks = asks
            cycle += 1

            # ── LOG (every 60s) ──
            if cycle % (1000 // CYCLE_MS * 60) == 0:
                mid = read_u64(mm, OFF_MICRO) / PRICE_SCALE
                toxic = read_u64(mm, OFF_TOXIC)
                log.info(f"L1 status: OBI={obi:+.3f} Skew=${skew_usd:+.2f} "
                        f"Mid=${mid:.0f} Toxic={toxic} Cycle={cycle}")

            # ── SLEEP ──
            elapsed = (time.monotonic() - t0) * 1000
            sleep_ms = max(1, CYCLE_MS - elapsed)
            time.sleep(sleep_ms / 1000)

        except KeyboardInterrupt:
            break
        except Exception as e:
            log.error(f"L1 error: {e}")
            time.sleep(1)

    # Clean shutdown — zero out skew
    write_i64(mm, OFF_L1_SKEW, 0)
    mm.close()
    os.close(fd)
    log.info("═══ L1 SHIELD STOPPED ═══")


if __name__ == "__main__":
    main()
